version: '3.3'
services:
  mysql:
    container_name: mariadb
    image: mariadb
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "casa"
      MYSQL_USER: "casa"
      MYSQL_PASSWORD: "casa"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:
